# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

title: Gefyra
email: michael@unikube.io
description: >-
  Blazingly-fast rocket, rock-solid, local application development arrow_right with Kubernetes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gefyra.dev" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  gefyrahq

search_enabled: true

# Build settings

# please use this for local development
# theme: "just-the-docs"

# this is used by GitHub
remote_theme: "just-the-docs/just-the-docs"
plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
custom_schemes:
  - gefyra
color_scheme: gefyra
ga_tracking: GTM-MZZHWCF
#
# Header
#
logo: "/assets/images/gefyra_logo.png"
# Aux links for the upper right navigation
aux_links:
  "[ CLI Reference ]":
    - "/reference/cli/"
  "Gefyra will become part of Unikube. Check it out!":
    - "//unikube.io"
#
# Footer
#
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/gefyrahq/gefyrahq.github.io"
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
