name: Links validator

on:
  schedule: 
    - cron:  '0 9 * * 1'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check links
        uses: lycheeverse/lychee-action@v1.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --verbose --no-progress --timeout 10 --max-concurrency 2 --exclude 'twitter.com' -- './**/*.md' './*.md' './**/**/*.md'
          output: ./lychee/out.md
      
      - name: Get current date
        id: date
        run: echo "::set-output name=now::$(date +'%d-%m-%Y')"
        
      - name: Create issue when fail
        if: ${{ steps.lychee.outputs.exit_code }} != 0
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Automated Links Checker Report for ${{ steps.date.outputs.now }}
          content-filepath: ./lychee/out.md
          labels: links validator

